<script lang="ts">
	const SCRIPT_OPEN = '<' + 'script lang="ts">';
	const SCRIPT_CLOSE = '</' + 'script>';
	const LB = '{';
	const RB = '}';
</script>

<svelte:head>
	<title>API Reference — svelte-fluid</title>
	<meta name="description" content="Imperative control of svelte-fluid via FluidHandle — inject splats, pause/resume, and more." />
</svelte:head>

<h1>API Reference</h1>
<p class="subtitle">Imperative control via <code>FluidHandle</code>.</p>

<p>
	While the <code>&lt;Fluid&gt;</code> component is primarily declarative (props in, simulation out),
	sometimes you need imperative control: injecting splats from application logic, pausing the
	simulation in response to an event, or querying the engine state. The <code>FluidHandle</code>
	interface provides this.
</p>

<h2>Getting the Handle</h2>

<p>
	Use Svelte's <code>bind:this</code> to capture a reference to the component instance. The
	<code>handle</code> property exposes the imperative API.
</p>

<pre><code>{SCRIPT_OPEN}
  import {LB} Fluid {RB} from 'svelte-fluid';
  import type {LB} FluidHandle {RB} from 'svelte-fluid';

  let fluidRef: {LB} handle: FluidHandle {RB};
{SCRIPT_CLOSE}

&lt;Fluid bind:this={LB}fluidRef{RB} /&gt;

&lt;button onclick={LB}() =&gt; fluidRef.handle.randomSplats(5){RB}&gt;
  Add splats
&lt;/button&gt;</code></pre>

<p>
	The same pattern works with presets — every preset component exposes the same
	<code>handle</code> property:
</p>

<pre><code>{SCRIPT_OPEN}
  import {LB} LavaLamp {RB} from 'svelte-fluid';
  import type {LB} FluidHandle {RB} from 'svelte-fluid';

  let lampRef: {LB} handle: FluidHandle {RB};
{SCRIPT_CLOSE}

&lt;LavaLamp bind:this={LB}lampRef{RB} /&gt;</code></pre>

<hr />

<h2>FluidHandle Methods</h2>

<h3>splat(x, y, dx, dy, color)</h3>

<p>Inject a single splat at the given position with velocity and color.</p>

<table>
	<thead>
		<tr>
			<th>Parameter</th>
			<th>Type</th>
			<th>Description</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td><code>x</code></td>
			<td><code>number</code></td>
			<td>X position in normalized coords (0 = left, 1 = right)</td>
		</tr>
		<tr>
			<td><code>y</code></td>
			<td><code>number</code></td>
			<td>Y position in normalized coords (0 = bottom, 1 = top)</td>
		</tr>
		<tr>
			<td><code>dx</code></td>
			<td><code>number</code></td>
			<td>X velocity (raw value, <strong>not</strong> scaled by <code>splatForce</code>)</td>
		</tr>
		<tr>
			<td><code>dy</code></td>
			<td><code>number</code></td>
			<td>Y velocity (raw value, <strong>not</strong> scaled by <code>splatForce</code>)</td>
		</tr>
		<tr>
			<td><code>color</code></td>
			<td><code>RGB</code></td>
			<td>Color in 0-1 linear range. Values above 1 are valid HDR and appear as bloom highlights.</td>
		</tr>
	</tbody>
</table>

<pre><code>// Inject a bright red splat at the center moving rightward
fluidRef.handle.splat(0.5, 0.5, 500, 0, {LB} r: 1.5, g: 0.1, b: 0.1 {RB});</code></pre>

<p>
	Velocity values are in pixels per frame and written directly to the splat shader uniform.
	Unlike pointer-driven splats, these are <strong>not</strong> multiplied by <code>splatForce</code>.
	Pick the absolute magnitude you want. Typical values range from 100 (gentle) to 1000 (forceful).
</p>

<h3>randomSplats(count)</h3>

<p>Push N additional random splats onto the splat queue. Colors are generated by the engine's internal <code>generateColor</code> function.</p>

<table>
	<thead>
		<tr>
			<th>Parameter</th>
			<th>Type</th>
			<th>Description</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td><code>count</code></td>
			<td><code>number</code></td>
			<td>Number of random splats to inject</td>
		</tr>
	</tbody>
</table>

<pre><code>// Add 10 random splats
fluidRef.handle.randomSplats(10);</code></pre>

<h3>pause()</h3>

<p>
	Stop the animation loop. The WebGL context stays alive but no frames are requested. Call
	<code>resume()</code> to restart. Idempotent — calling <code>pause()</code> on an
	already-paused engine is a no-op.
</p>

<pre><code>fluidRef.handle.pause();</code></pre>

<h3>resume()</h3>

<p>
	Restart the animation loop after a <code>pause()</code>. Idempotent — calling
	<code>resume()</code> on an already-running engine is a no-op.
</p>

<pre><code>fluidRef.handle.resume();</code></pre>

<h3>isPaused</h3>

<p>Readonly boolean property indicating whether the engine's animation loop is currently paused.</p>

<pre><code>if (fluidRef.handle.isPaused) {LB}
  fluidRef.handle.resume();
{RB}</code></pre>

<hr />

<h2>Types</h2>

<h3>RGB</h3>

<p>A simple color triple with <code>r</code>, <code>g</code>, <code>b</code> number fields. The unit convention depends on context:</p>

<table>
	<thead>
		<tr>
			<th>Context</th>
			<th>Range</th>
			<th>Notes</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td><code>backColor</code> prop</td>
			<td>0-255</td>
			<td>CSS-style. Normalized internally before reaching the shader.</td>
		</tr>
		<tr>
			<td><code>FluidHandle.splat()</code> color</td>
			<td>0-1</td>
			<td>Linear. Values above 1 are valid HDR and create bloom highlights.</td>
		</tr>
		<tr>
			<td><code>PresetSplat.color</code></td>
			<td>0-1</td>
			<td>Linear. Same convention as <code>splat()</code>.</td>
		</tr>
		<tr>
			<td><code>revealCoverColor</code>, <code>revealAccentColor</code>, <code>revealFringeColor</code></td>
			<td>0-1</td>
			<td>Linear.</td>
		</tr>
	</tbody>
</table>

<pre><code>interface RGB {LB}
  r: number;
  g: number;
  b: number;
{RB}</code></pre>

<h3>PresetSplat</h3>

<p>
	Declarative initial splat consumed once at engine construction. Used by preset wrappers
	to paint a deterministic opening scene.
</p>

<table>
	<thead>
		<tr>
			<th>Field</th>
			<th>Type</th>
			<th>Description</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td><code>x</code></td>
			<td><code>number</code></td>
			<td>X position, 0-1 (left to right)</td>
		</tr>
		<tr>
			<td><code>y</code></td>
			<td><code>number</code></td>
			<td>Y position, 0-1 (bottom to top)</td>
		</tr>
		<tr>
			<td><code>dx</code></td>
			<td><code>number</code></td>
			<td>X velocity (raw, not scaled by <code>splatForce</code>)</td>
		</tr>
		<tr>
			<td><code>dy</code></td>
			<td><code>number</code></td>
			<td>Y velocity (raw, not scaled by <code>splatForce</code>)</td>
		</tr>
		<tr>
			<td><code>color</code></td>
			<td><code>RGB</code></td>
			<td>Color in 0-1 linear range (HDR values above 1 are valid)</td>
		</tr>
	</tbody>
</table>

<pre><code>interface PresetSplat {LB}
  x: number;
  y: number;
  dx: number;
  dy: number;
  color: RGB;
{RB}</code></pre>

<hr />

<h2>FluidEngine (Advanced)</h2>

<p>
	For advanced users who need framework-agnostic fluid simulation, the <code>FluidEngine</code>
	class is available as a direct import. It is the WebGL engine that powers the
	<code>&lt;Fluid&gt;</code> component, but it has no Svelte dependency.
</p>

<pre><code>import {LB} FluidEngine {RB} from 'svelte-fluid/engine/FluidEngine';</code></pre>

<p>
	The engine is constructed with a <code>canvas</code> element and a <code>config</code> object
	matching the <code>FluidConfig</code> interface. It exposes the same <code>splat()</code>,
	<code>randomSplats()</code>, <code>pause()</code>, <code>resume()</code>, and
	<code>isPaused</code> API as <code>FluidHandle</code>, plus additional methods:
</p>

<ul>
	<li><code>setConfig(config)</code> — update configuration at runtime (respects the 4-bucket system)</li>
	<li><code>dispose()</code> — free all GPU resources (textures, framebuffers, programs). The WebGL context is left intact for potential reuse.</li>
</ul>

<p>
	Architecture invariant: the engine never imports Svelte. It is fully framework-agnostic and
	could be used with React, vanilla JS, or any other framework. The Svelte component is a thin
	wrapper that handles lifecycle, sizing, and prop reactivity.
</p>
